### ISSUE TITLE
npm start doesn't work

### ISSUE THREAD

**Issue by NiallJoeMaher** [FrontendMasters/2015-02-13-React#6]
Here are the contents of the npm depug log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Y580\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v7.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle frontendmasters@1.0.0~prestart: frontendmasters@1.0.0
6 silly lifecycle frontendmasters@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle frontendmasters@1.0.0~start: frontendmasters@1.0.0
8 verbose lifecycle frontendmasters@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle frontendmasters@1.0.0~start: PATH: C:\Users\Y580\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Y580\Desktop\FrontEnd_Masters\react\2015-02-13-React\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Python34\;C:\Python34\Scripts;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Lenovo\Bluetooth Software\;C:\Program Files\Lenovo\Bluetooth Software\syswow64;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Users\Y580\Desktop\Developer Tools\wamp\bin\php\php5.5.12;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Brackets\command;C:\Ruby23-x64\bin;C:\Program Files\nodejs;C:\Users\Y580\AppData\Local\atom\bin;C:\Users\Y580\AppData\Local\.meteor\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Y580\AppData\Roaming\npm
10 verbose lifecycle frontendmasters@1.0.0~start: CWD: C:\Users\Y580\Desktop\FrontEnd_Masters\react\2015-02-13-React
11 silly lifecycle frontendmasters@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dev-server --inline --no-info --content-base excercises' ]
12 silly lifecycle frontendmasters@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle frontendmasters@1.0.0~start: Failed to exec start script
14 verbose stack Error: frontendmasters@1.0.0 start: `webpack-dev-server --inline --no-info --content-base excercises`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Y580\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Y580\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid frontendmasters@1.0.0
16 verbose cwd C:\Users\Y580\Desktop\FrontEnd_Masters\react\2015-02-13-React
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Y580\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.1.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error frontendmasters@1.0.0 start: `webpack-dev-server --inline --no-info --content-base excercises`
22 error Exit status 1
23 error Failed at the frontendmasters@1.0.0 start script 'webpack-dev-server --inline --no-info --content-base excercises'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the frontendmasters package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --inline --no-info --content-base excercises
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs frontendmasters
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls frontendmasters
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by yangashley** [comment]
I had the same problem. I was able to fix it by running: 

`npm install webpack-dev-server@1.8.0 --save`
and then `npm start` worked fine.

https://github.com/Khan/perseus/issues/80

Hope that helps!
